// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1nDIly3NDgqv5IeXe4N7Y21T_XwU8lNc',
    appId: '1:1015356747305:web:a49fb5a22d29068325b638',
    messagingSenderId: '1015356747305',
    projectId: 'socialmediaapp-72761',
    authDomain: 'socialmediaapp-72761.firebaseapp.com',
    storageBucket: 'socialmediaapp-72761.firebasestorage.app',
    measurementId: 'G-VNGQFCC764',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7iRjKmCIpcGgAM5efnszkrmu_F-99Sk',
    appId: '1:1015356747305:android:40f9a0ac895f2abf25b638',
    messagingSenderId: '1015356747305',
    projectId: 'socialmediaapp-72761',
    storageBucket: 'socialmediaapp-72761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5XYqsnw4Kht88sbIDRFl0Fttbos9j08',
    appId: '1:1015356747305:ios:6f767ae0130c094125b638',
    messagingSenderId: '1015356747305',
    projectId: 'socialmediaapp-72761',
    storageBucket: 'socialmediaapp-72761.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
